apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "word-count.fullname" . }}
  labels:
    app: {{ template "word-count.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "word-count.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [
          "/go/bin/run-consumer", "serve",
          "--wordcount.N=3",
          "--consumer.module=/go/bin/counter.so",
          "--consumer.zone={{ .Values.zone }}",
          "--consumer.port={{ .Values.service.port }}",
          "--broker.address={{ .Values.gazette.endpoint }}",
          "--broker.cache.size=256",
          "--etcd.address={{ .Values.etcd.endpoint }}",
          "--etcd.prefix={{ .Values.etcd.prefix }}",
          "--debug.port={{ .Values.service.monitoringPort }}",
        ]
        env:
        - name: CONSUMER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CONSUMER_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: {{ .Values.service.port }}
          name: service
        - containerPort: {{ .Values.service.monitoringPort }}
          name: monitoring
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.port }}
      terminationGracePeriodSeconds: 21600
